### ISSUE TITLE
Pause menu 

### ISSUE THREAD

**Issue by houss1evengames** [eg-ayoub/TheMansionDE#46] opened 2019-11-01 10:22 UTC
Opening a new issue for the pause menu , I suggest to add this : 

- [ ] Have ESC close the pause menu as well.
- [ ] option to turn on/off the music. 
- [ ] controls : displays detailed controls screen.

**Comment by eg-ayoub** [comment] 2019-11-01 10:51
duplicate of #2 , please post the comment on the right issue

**Closed as completed by eg-ayoub** 2019-11-01 10:51 UTC
Labels: enhancement
